name: Auto Assign Author
on:
  pull_request:
    types: [opened]
jobs:
  assing:
    if: github.actor != 'dependbot[bot]'

    name: Assing author to PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@v1
